# Generated by Django 5.2.1 on 2025-05-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='brand',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='form',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
