# Generated by Django 5.2.1 on 2025-05-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0003_alter_orderitem_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='medicine',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='payed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='returned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
