# Generated by Django 5.2.1 on 2025-05-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0004_remove_cartitem_cart_remove_cartitem_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='siunit',
            field=models.CharField(default='', max_length=20),
        ),
    ]
