# Generated by Django 5.2.1 on 2025-05-25 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0007_rename_total_bill_sale_grandtotal_sale_subtotal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='payed',
            new_name='paid',
        ),
    ]
