# Generated by Django 5.2.1 on 2025-05-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0008_rename_payed_sale_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
