# Generated by Django 5.2.1 on 2025-05-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0010_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
