# Generated by Django 5.2.1 on 2025-05-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_brand', models.CharField(max_length=20)),
                ('med_name', models.CharField(max_length=20)),
                ('med_batch', models.IntegerField()),
                ('med_expiry', models.DateField()),
                ('med_par', models.IntegerField()),
                ('med_stock', models.IntegerField()),
                ('med_unitprice', models.IntegerField()),
                ('med_boxprice', models.IntegerField()),
                ('med_boxQ', models.IntegerField()),
                ('med_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_brand', models.CharField(max_length=20)),
                ('order_name', models.CharField(max_length=20)),
                ('order_stock', models.IntegerField()),
                ('order_price', models.IntegerField()),
            ],
        ),
    ]
