# Generated by Django 5.2.1 on 2025-05-19 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_order_order_price_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='med_dose',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='med_dose_unit',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='order_dose',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_dose_unit',
            field=models.CharField(default='', max_length=20),
        ),
    ]
