# Generated by Django 5.2.1 on 2025-05-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='med_dose',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='med_dose_unit',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='order_dose',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_dose_unit',
            field=models.CharField(default=''),
        ),
    ]
